### PR TITLE
Travis integration

### PR DESCRIPTION
**Pull request by zaucker**
- Setup Travis automated testing according to https://docs.travis-ci.com/user/languages/perl6
- "Nicer" layout on META.info

(sorry for the combined PR, I am still struggeling with git).

I am also not sure why the pull requests contains the previous changes to t/00_use_meta.t again. I must be doing something wrong.

### CODE REVIEW

**Comment by Skarsnik** [comment]
To be honest I have no idea how to regroup commit with git either :)

**Comment by zaucker** [comment]
:-)

On Thu, 14 Jan 2016, Skarsnik wrote:

> To be honest I have no idea how to regroup commit with git either :)

## 

Oetiker+Partner AG              tel: +41 62 775 9903 (direct)
Fritz Zaucker                        +41 62 775 9900 (switch board)
Aarweg 15                            +41 79 675 0630 (mobile)
CH-4600 Olten                   fax: +41 62 775 9905
Schweiz                         web: www.oetiker.ch

**Comment by zaucker** [comment]
Can you switch on Travis testing at

```
https://travis-ci.org/profile/Skarsnik
```

You might have to do the first run by pushing some change into the
repository. After that it should be automatically checked by any push into
the repo.

The entry at modules.perl6.org probably will then update the Travis column
automatically somehow ...

Cheers,
Fritz

On Thu, 14 Jan 2016, Skarsnik wrote:

> Merged #5.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/Skarsnik/perl6-config-simple/pull/5#event-515006354

## 

Oetiker+Partner AG              tel: +41 62 775 9903 (direct)
Fritz Zaucker                        +41 62 775 9900 (switch board)
Aarweg 15                            +41 79 675 0630 (mobile)
CH-4600 Olten                   fax: +41 62 775 9905
Schweiz                         web: www.oetiker.ch

**Comment by zaucker** [comment]
Oops, it is already being displayed as "passing".  Sorry, I guess I hadn't
reloaded the modules page in my browser ...

On Thu, 14 Jan 2016, Fritz Zaucker wrote:

> Can you switch on Travis testing at
> 
>   https://travis-ci.org/profile/Skarsnik
> 
> You might have to do the first run by pushing some change into the
> repository. After that it should be automatically checked by any push into
> the repo.
> 
> The entry at modules.perl6.org probably will then update the Travis column
> automatically somehow ...
> 
> Cheers,
> Fritz
> 
> On Thu, 14 Jan 2016, Skarsnik wrote:
> 
> > Merged #5.
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/Skarsnik/perl6-config-simple/pull/5#event-515006354

## 

Oetiker+Partner AG              tel: +41 62 775 9903 (direct)
Fritz Zaucker                        +41 62 775 9900 (switch board)
Aarweg 15                            +41 79 675 0630 (mobile)
CH-4600 Olten                   fax: +41 62 775 9905
Schweiz                         web: www.oetiker.ch

**Pull request merged**
